services:
  inventory-service:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}       # Nombre de la base de datos
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}       # Usuario de la base de datos
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}   # Contraseña del usuario
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
